# Generated by Django 5.2.4 on 2025-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='company_stage',
            field=models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'MVP'), ('early', 'Early Stage'), ('growth', 'Growth Stage'), ('scale', 'Scale Up')], default='idea', max_length=50),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='funding_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='industries',
            field=models.ManyToManyField(related_name='entrepreneurs', to='Entrepreneurs.industry'),
        ),
    ]
