# Generated by Django 5.2.4 on 2025-08-17 21:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0003_comment_post_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='github_profile',
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='twitter_handle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='funding_need',
            field=models.CharField(choices=[('not_specified', 'Not Specified'), ('seed', 'Seed Funding'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('other', 'Other')], default='not_specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='funding_raised',
            field=models.CharField(choices=[('no_funding', 'No Funding'), ('0-50k', '$0 - $50K'), ('50k-500k', '$50K - $500K'), ('500k-5m', '$500K - $5M'), ('5m-50m', '$5M - $50M'), ('50m+', '$50M+')], default='no_funding', max_length=50),
        ),
        migrations.RemoveField(
            model_name='entrepreneurprofile',
            name='industries',
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='revenue',
            field=models.CharField(choices=[('no_revenue', 'No Revenue'), ('0-10k', '$0 - $10K'), ('10k-100k', '$10K - $100K'), ('100k-1m', '$100K - $1M'), ('1m-10m', '$1M - $10M'), ('10m+', '$10M+')], default='no_revenue', max_length=50),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='startup_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='team_size',
            field=models.CharField(choices=[('1', '1 person'), ('2-5', '2-5 people'), ('6-10', '6-10 people'), ('11-25', '11-25 people'), ('26-50', '26-50 people'), ('50+', '50+ people')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='valuation',
            field=models.CharField(choices=[('not_specified', 'Not Specified'), ('0-1m', '$0 - $1M'), ('1m-10m', '$1M - $10M'), ('10m-100m', '$10M - $100M'), ('100m-1b', '$100M - $1B'), ('1b+', '$1B+')], default='not_specified', max_length=50),
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('file_data', models.BinaryField(blank=True, editable=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='Entrepreneurs.post')),
            ],
        ),
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='industries',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
