# Generated by Django 5.2.4 on 2025-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0006_post_saved_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmedia',
            options={'ordering': ['position', 'uploaded_at', 'id']},
        ),
        migrations.AddField(
            model_name='postmedia',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
