# Generated by Django 5.2.4 on 2025-08-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0007_alter_postmedia_options_postmedia_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
