# Generated by Django 5.2.4 on 2025-08-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0009_message_file_data_message_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='industries',
            field=models.CharField(blank=True, choices=[('ai', 'Artificial Intelligence (AI)'), ('fintech', 'Fintech'), ('healthtech', 'Healthtech'), ('enterprise_saas', 'Enterprise AI SaaS'), ('logistics', 'Logistics & Supply Chain Tech'), ('quantum', 'Quantum Computing'), ('insurtech', 'InsurTech'), ('spacetech', 'SpaceTech'), ('creator_tools', 'Creator Economy Tools'), ('cleantech', 'CleanTech & Green Energy')], max_length=500),
        ),
    ]
