# Generated by Django 5.2.4 on 2025-08-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0010_alter_entrepreneurprofile_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='industry',
            field=models.CharField(choices=[('ai', 'Artificial Intelligence (AI)'), ('fintech', 'Fintech'), ('healthtech', 'Healthtech'), ('enterprise_saas', 'Enterprise AI SaaS'), ('logistics', 'Logistics & Supply Chain Tech'), ('quantum', 'Quantum Computing'), ('insurtech', 'InsurTech'), ('spacetech', 'SpaceTech'), ('creator_tools', 'Creator Economy Tools'), ('cleantech', 'CleanTech & Green Energy')], max_length=100),
        ),
    ]
