# Generated by Django 5.2.4 on 2025-08-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0012_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
