# Generated by Django 5.2.4 on 2025-08-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0014_user_can_show_network_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_show_network',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='show_followers',
            field=models.BooleanField(default=True, help_text='Allow others to see your followers/network'),
        ),
    ]
