# Generated by Django 5.2.4 on 2025-08-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0016_meeting'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('investor', 'Investor'), ('entrepreneur', 'Entrepreneur')], default='entrepreneur', max_length=20),
        ),
    ]
