# Generated by Django 5.2.4 on 2025-08-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='investment_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(limit_choices_to={'role': 'investor'}, on_delete=django.db.models.deletion.CASCADE, to='Entrepreneurs.user')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_investments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preferred_industries', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.OneToOneField(limit_choices_to={'role': 'investor'}, on_delete=django.db.models.deletion.CASCADE, to='Entrepreneurs.user')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('investment_interests', models.TextField(blank=True, null=True)),
                ('portfolio_companies', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'investor'}, on_delete=django.db.models.deletion.CASCADE, to='Entrepreneurs.user')),
            ],
        ),
    ]
