# Generated by Django 5.2.4 on 2025-08-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0002_industry_remove_entrepreneurprofile_profile_image_and_more'),
        ('Investors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofile',
            name='portfolio_companies',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='firm_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='max_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='min_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='notable_exits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='number_of_investments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='preferred_stages',
            field=models.CharField(blank=True, help_text='Comma-separated stages', max_length=255),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='total_investments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='investment_interests',
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='investment_interests',
            field=models.ManyToManyField(related_name='interested_investors', to='Entrepreneurs.industry'),
        ),
    ]
