# Generated by Django 5.2.4 on 2025-08-17 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0003_comment_post_alter_activitylog_options_and_more'),
        ('Investors', '0002_remove_investorprofile_portfolio_companies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorportfolio',
            old_name='preferred_industries',
            new_name='notable_exits',
        ),
        migrations.RemoveField(
            model_name='investmentdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='notable_exits',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='number_of_investments',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='total_investments',
        ),
        migrations.AddField(
            model_name='investmentdocument',
            name='file_data',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentdocument',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentdocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investorportfolio',
            name='number_of_investments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='investmentdocument',
            name='investor',
            field=models.ForeignKey(limit_choices_to={'role': 'investor'}, on_delete=django.db.models.deletion.CASCADE, related_name='investment_documents', to='Entrepreneurs.user'),
        ),
        migrations.AlterField(
            model_name='investorportfolio',
            name='investor',
            field=models.OneToOneField(limit_choices_to={'role': 'investor'}, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='Entrepreneurs.user'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='investment_interests',
            field=models.ManyToManyField(blank=True, related_name='interested_investors', to='Entrepreneurs.industry'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'investor'}, on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to='Entrepreneurs.user'),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
