# Generated by Django 5.2.4 on 2025-08-17 21:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0003_rename_preferred_industries_investorportfolio_notable_exits_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorprofile',
            name='investment_interests',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='max_investment',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='min_investment',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='preferred_stages',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='twitter_handle',
        ),
        migrations.RemoveField(
            model_name='investorprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='investment_size',
            field=models.CharField(choices=[('not_specified', 'Not Specified'), ('0-50k', '$0 - $50K'), ('50k-500k', '$50K - $500K'), ('500k-5m', '$500K - $5M'), ('5m-50m', '$5M - $50M'), ('50m+', '$50M+')], default='not_specified', max_length=50),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='investment_stage',
            field=models.CharField(choices=[('not_specified', 'Not Specified'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('growth', 'Growth'), ('late_stage', 'Late Stage')], default='not_specified', max_length=50),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='notable_exits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='portfolio_companies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investorprofile',
            name='preferred_industries',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='investorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
