# Generated by Django 5.2.4 on 2025-08-23 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepreneurs', '0011_alter_startup_industry'),
        ('Investors', '0005_alter_investorprofile_preferred_industries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=255)),
                ('target_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity_offered', models.DecimalField(decimal_places=2, help_text='Total equity offered (%)', max_digits=5)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('successful', 'Successful'), ('failed', 'Failed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='Entrepreneurs.startup')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('funding_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='Investors.fundinground')),
                ('investor', models.ForeignKey(limit_choices_to={'role': 'investor'}, on_delete=django.db.models.deletion.CASCADE, related_name='investment_commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('funding_round', 'investor')},
            },
        ),
    ]
