# Generated by Django 5.2.4 on 2025-08-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investors', '0006_fundinground_investmentcommitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
